### ISSUE TITLE
#17 Write tests following createUser / first post setup

### ISSUE THREAD

**Issue by edgarfinn** [edgarfinn/Chatter-Social-Network#23]
There seems to be an issue testing updates to the database.

Modules ```updateStore``` and ```resetTestStore``` both seem to behave the same. 

Common error message is 
```bash
    SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)

      2 | 
      3 | module.exports = function(filePath) {
    > 4 |   return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
      5 | }
      6 | 
      
      at Object.<anonymous>.module.exports (modules/ReadStore/readStore.js:4:15)
      at Object.<anonymous>.module.exports (modules/PostMessage/postMessage.js:14:15)
      at Object.<anonymous> (modules/PostMessage/postMessage.test.js:68:5)
```

**Comment by edgarfinn** [comment]
Try: 
- removing ```module.exports``` from backup database and using only fs.readFile to revert database. Beware of any need to stringify / parse the backup store.

- removing ```Sync``` from ```readStore```, and adding an error-handling hard-coded callback to see if this yields any further clues.
